import Head from 'next/head'
import Footer from "./Footer";
import Header from "./Header";
import styles from '../styles/Home.module.css'

const Layout = ({ children }) => {
    return (
        <div className="main">
            <Head>
                <title>Learn with Akbar</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <Header />{children}</div>
            <Footer />
        </div>
    );
}

export default Layout;